image: $CI_REGISTRY/courses/dit342/2023/group-22-web

# Cache modules in between jobs per-branch
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - server/node_modules/

stages:
  - build
  - test
  - deploy

build:
  stage: build
  tags:
    - docker
  script:
    - apt install g++
    - cd server
    - rm -rf node_modules
    - npm install
    - npm rebuild bcrypt

test:
  stage: test
  tags:
    - docker
  variables:
    MONGODB_URI: "mongodb://mongo:27017/serverTestDB"
  services:
    - name: mvertes/alpine-mongo:latest
      alias: mongo
  script:
    - apt install -y procps
    - cd server
    - npm run ci-test
    # this echo, and the 'ls > /dev/null' (in package.json, the newman script)
    # are needed, otherwise the pipeline gets stucks, even though the tests pass
    # we tried several things, and spent hours on this, but in the end only
    # this worked, and with the submission coming closer, we'll keep it at this.
    # Surprisingly, chaining it with '&& exit 0' instead of 'ls' doesn't work
    # either, and the pipeline gets stuck again.
    - echo $?
deploy:
  stage: deploy
  tags:
    - docker
  image: ruby:alpine
  script:
    - apk update && apk add git curl
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  environment:
    name: production
    url: https://$HEROKU_APP_NAME.herokuapp.com/
  only:
    refs:
      - master
    variables:
      - $HEROKU_APP_NAME
      - $HEROKU_API_KEY
